### ISSUE TITLE
Won't wrap doubly indented text inside Python docstring

### ISSUE THREAD

**Issue by gauss256** [stkb/Rewrap#90] opened 2018-06-10 20:56 UTC
This may be related to #89.

If I try to wrap a single paragraph inside a docstring that is indented two or more levels deep, it doesn't do anything. Text that is indented zero or one levels wraps without a problem. 

Using dots to indicate leading spaces,

Works:
```Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris```

Works:
```....Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris```

Doesn't work:
```........Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris```

**Comment by stkb** [comment] 2020-06-02 13:20
Closing as duplicate of #89. It's not working because the content is being processed as markdown instead of rST.

**Closed by stkb** 2020-06-02 13:20 UTC
Labels: duplicate
