### ISSUE TITLE
VSCode 1.47.2 - Win10 20H2 - rewrap error - developer console dump included.

### ISSUE THREAD

**Issue by StewBC** [stkb/Rewrap#225] opened 2020-07-21 18:25 UTC
console.ts:137 [Extension Host] ====== Rewrap: Error ======
t.log @ console.ts:137
console.ts:137 [Extension Host] DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model3) has been disposed    at Object.t.disposed (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:47:343)    at e.$tryApplyEdits (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4183:448)    at p._doInvokeHandler (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4258:757)    at p._invokeHandler (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4258:449)    at p._receiveRequest (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4257:120)    at p._receiveOneMessage (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4255:970)    at file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4254:161    at c.fire (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)    at v.fire (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:430:733)    at t.PersistentProtocol._receiveMessage (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:435:38)    at file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:432:243    at c.fire (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)    at g.acceptChunk (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:428:234)    at file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:427:604    at Socket.t (file:///C:/Users/swessels/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:436:655)    at Socket.emit (events.js:203:13)    at addChunk (_stream_readable.js:295:12)    at readableAddChunk (_stream_readable.js:276:11)    at Socket.Readable.push (_stream_readable.js:210:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues
t.log @ console.ts:137
---
The content I am trying to wrap is in a plain text file, and is this:
$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$1C,$58,$58,$58,$58,$58,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$1C,$58,$58,$58,$58,$58,$58,$58,$58,$8F,$8F,$8F,$1C,$1C,$1C,$1C,$58,$58,$58,$58,$58,$58,$58,$58,$58,$8F,$8F,$8F,$1C,$1C,$1C,$58,$58,$58,$58,$58,$58,$58,$58,$58,$58,$8F,$8F,$8F,$1C,$1C,$58,$58,$58,$58,$58,$58,$58,$58,$58,$58,$18,$8F,$8F,$8F,$1C,$1C,$58,$58,$58,$58,$58,$58,$58,$18,$18,$18,$18,$8F,$8F,$8F,$1C,$1C,$58,$58,$58,$58,$58,$58,$18,$18,$18,$18,$18,$8F,$8F,$8F,$1C,$58,$58,$58,$58,$58,$58,$18,$18,$18,$18,$18,$18,$8F,$8F,$8F,$1C,$58,$58,$58,$58,$58,$18,$18,$18,$18,$18,$18,$18,$8F,$8F,$8F,$1C,$58,$58,$58,$58,$58,$18,$18,$18,$18,$18,$18,$18,$8F,$8F,$8F,$1C,$58,$58,$58,$58,$58,$18,$18,$18,$18,$18,$18,$18,$8F,$8F,$8F,$1C,$58,$58,$58,$58,$18,$18,$18,$18,$18,$18,$18,$18

**Comment by StewBC** [comment] 2020-07-21 18:36
More info.  I realize there are no spaces so rewrap can't wrap, but IMHO, throwing an error isn't the right solution.  A different message about there being no wrapping opportunity or something else along those lines would be more helpful.  Also, doing nothing isn't desirable because that would look like nothing happened, vs nothing could happen.  I am looking at it from my (user) perspective and how I was just confused about rewrap not working when in fact it did work after I inserted spaces after the comma's.  It took me some time and looking at the error log was no clue that I had didn't have workable (wrap-able) content.

**Comment by stkb** [comment] 2020-07-24 17:49
I'm afraid I don't know what's going on there. From the stack trace it seems like an error in VSCode itself, there's no code from Rewrap there. I can't reproduce it either (it no-ops, which is expected).

I appreciate that in your case a no-op may be confusing, but this is quite an edge case. Also it may be sometimes desirable to split on commas, but other times maybe not. So I'm not really going to change anything here unless other people come feeling the same.

I'll leave this open in case other people can shed some light on this error.

**Comment by StewBC** [comment] 2020-07-24 17:59
Completely understand - it is actually after all (my) human error that led to this in the first place ;)  Thank you for taking the time to look.

**Comment by stkb** [comment] 2022-01-17 14:33
Closing as dup of #100

**Closed by stkb** 2022-01-17 14:33 UTC
