### ISSUE TITLE
Updating wrappingColumn requires restarting VSCode to take effect

### ISSUE THREAD

**Issue by GreenGremlin** [stkb/Rewrap#197] opened 2020-05-19 16:56 UTC
Updating the `rewrap.wrappingColumn` setting seems to take a restart of VSCode to take effect. It seems that updating a setting for an extension should not require restarting the editor.

**Comment by stkb** [comment] 2020-05-21 08:10
Duplicate of #99 (a fix is on the way)

**Closed by stkb** 2020-05-21 08:10 UTC
Labels: duplicate

**Comment by stkb** [comment] 2020-05-21 11:11
See https://github.com/stkb/Rewrap/issues/99#issuecomment-632027290
