### ISSUE TITLE
Markdown footnotes are not wrapped correctly

### ISSUE THREAD

**Issue by zandaleph** [stkb/Rewrap#188] opened 2020-04-26 16:26 UTC
Currently, an overlong footnote like so:

```
[^1]: I have a funny story about this that I am not quite prepared to tell at the moment but want to tell someday.
```

is not rewrapped, violating an 80 character limit.  Manually rewrapping to

```
[^1]: I have a funny story about this that I am not quite prepared to tell at
  the moment but want to tell someday.
```

which [follows guidelines for long footnotes](https://www.markdownguide.org/extended-syntax/#footnotes), is incorrectly rewrapped to

```
[^1]:

  I have a funny story about this that I am not quite prepared to tell at
  the moment but want to tell someday.
```

which is rendered as an empty footnotes and places an unwanted paragraph in the main text.

I would be able to work around this bug by simply allowing long-lined footnotes if I only had simple footnotes, but unfortunately more complicated footnotes, like this one from the footnote documentation above, are always mangled by rewrap.

```
[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

Would it be possible to add support for long footnotes and fix this bug?  Thank you.

**Comment by rossmacarthur** [comment] 2020-04-27 13:33
Problem the same as https://github.com/stkb/Rewrap/issues/63

**Comment by stkb** [comment] 2020-05-14 14:54
Closing as duplicate of #63. I did try to fix it but found I basically had to rewrite the markdown parser to fix that (and other) bugs, which is still a WIP

**Closed by stkb** 2020-05-14 14:54 UTC
Labels: duplicate
