### ISSUE TITLE
Intermittent NullReferenceException 

### ISSUE THREAD

**Issue by anticrisis** [stkb/Rewrap#62] opened 2018-01-03 20:59 UTC
This has happened twice to me today, both times immediately after I had triggered Shift-F12, Find All References for a symbol. It seems to be innocuous, because Shift-F12 succeeds, and subsequent uses don't seem to trigger the exception again.

This is the exception noted in the Activity Log:

`System.NullReferenceException: Object reference not set to an instance of an object. at VS.TextViewCreationListener.TextViewCreated(IWpfTextView textView) in C:\Users\Steve\Projects\Rewrap\vs\CommandFilter.cs:line 88 at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.<>c__DisplayClass244_0.<BindContentTypeSpecificAssets>b__1() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)`

Hopefully the source reference helps because I'm not sure how to get more useful information about this.

Visual Studio 2017 15.5.2 on Windows 10

**Comment by stkb** [comment] 2018-01-10 18:13
Thanks, I can repro it on v1.5.3 but it seems to be fixed in the latest version in master. I'll be publishing the next version (1.6.0) in the next couple of days.

**Comment by stkb** [comment] 2018-01-14 21:23
Turns out I was initially wrong, but I'm pretty sure I found the cause now. v1.6.0 has just been published; let me know if you're still experiencing this (or any other) issue.

**Closed by stkb** 2018-01-14 21:23 UTC
