### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by palango** [stkb/Rewrap#326] opened 2022-03-04 15:37 UTC
This happens in an rst document

VSCode 1.65.0
Rewrap 1.16.3

Error:
```
console.ts:137 [Extension Host] ====== Rewrap: Error ======
I @ console.ts:137
console.ts:137 [Extension Host] TypeError: e.System.Collections.IEnumerator.MoveNext is not a function
   at $c4c313718bcc393b$export$f7e9f41ea797a17 (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:7032:69)
   at $044d4a9a60b1f629$export$37f42de08e6cfa5e (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:9079:12)
   at /Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:12593:75
   at $c4c313718bcc393b$export$d65cb303b863e3bf (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:7082:17)
   at $840f1b1ae3c3949d$export$78262f0a7b75cf50 (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:12593:17)
   at $840f1b1ae3c3949d$export$2e6c959c16ff56b8 (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:12598:49)
   at $900a7436dc584467$export$6cb9d9886761bf2b (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:13052:23)
   at $fad922d34226e04f$var$doWrap (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:13601:22)
   at rewrapCommentCommand (/Users/paul/.vscode/extensions/stkb.rewrap-1.16.3/dist/Extension.js:13562:9)
   at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:31076
   at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:49106)
   at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:31063
   at f._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:30255)
   at f.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:30797)
   at n._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13812)
   at n._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13496)
   at n._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12158)
   at n._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10836)
   at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8945
   at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
   at w.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
   at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19017)
   at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34267
   at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
   at w.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
   at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19017)
   at s._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23598)
   at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21132
   at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
   at w.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
   at w.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15848)
   at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14978
   at Socket.P (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13790)
   at Socket.emit (events.js:315:20)
   at addChunk (internal/streams/readable.js:309:12)
   at readableAddChunk (internal/streams/readable.js:284:9)
   at Socket.Readable.push (internal/streams/readable.js:223:10)
   at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
log.ts:313   ERR [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
at https://github.com/stkb/vscode-rewrap/issues
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues
I @ console.ts:137

**Comment by stkb** [comment] 2022-03-04 16:09
Hi this seems to be the same error as #311. Can you reproduce it?

**Comment by palango** [comment] 2022-03-04 16:14
> Can you reproduce it?

It happened on every invocation of the rewrap command, independent of the language.

After a restart everything works again though.

**Comment by stkb** [comment] 2022-03-04 16:27
> After a restart everything works again though.

Thanks, yeah that matches https://github.com/stkb/Rewrap/issues/311#issuecomment-1054683182. This is proving difficult to track down the cause. However I'm going to close this issue in favor of #311.

**Closed as completed by stkb** 2022-03-04 16:27 UTC
