### ISSUE TITLE
Consider publishing to the Open VSX Registry

### ISSUE THREAD

**Issue by Siosm** [stkb/Rewrap#226] opened 2020-07-25 10:26 UTC
First, let me say thank you for creating this extension!

I am a VSCodium user and the default Microsoft extension marketplace has been changed to the Open VSX Registry. Could you publish your extension there too? See https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace.

Thanks!

**Comment by stkb** [comment] 2020-08-01 09:54
Dupe of #210 but it's now published at https://open-vsx.org/extension/stkb/rewrap :)

**Closed by stkb** 2020-08-01 09:54 UTC

**Comment by Siosm** [comment] 2020-08-01 10:11
Thanks!
