### ISSUE TITLE
feature request: auto-fill-mode

### ISSUE THREAD

**Issue by dmose** [stkb/Rewrap#45] opened 2017-08-10 13:55 UTC
First off, thanks for writing Rewrap; this is really great and already makes editing code a bunch easier!

An even higher level of awesome would be to support the equivalent of emacs auto-fill mode, where it fixes up wrapper automagically while you type.

**Comment by stkb** [comment] 2017-08-10 16:29
Hi and thanks for the feedback and request!

I've seen this mentioned elsewhere so have thought about it a little; have just been waiting for someone to request it.

It's got some tricky aspects and might not be battery friendly. But I will look into it after the next release.

**Comment by dmose** [comment] 2017-08-10 22:10
Wonderful; thanks!  And I can totally see how there would be nuance to implementing this.

**Comment by giggio** [comment] 2017-10-02 22:40
I would also love to have this feature. We should be able to turn it on or off. It should be off by default.

**Comment by stkb** [comment] 2017-10-07 17:46
@giggio Agreed: there'll be a command to toggle it. I am working on this and #46 at the moment.

**Comment by calrsom** [comment] 2017-11-01 17:44
Would love to see this for markdown, comments, and other documentation/non-code blocks!

**Comment by stkb** [comment] 2017-11-24 20:22
I now have a beta version with this feature, to try out.

<img src="https://user-images.githubusercontent.com/6125444/33223032-5f07a208-d15c-11e7-91e9-353f5703ea04.gif" width="400" />

The feature works similarly to that in emacs, in that it only triggers after pressing space or enter if the cursor is past the wrapping column, and it only wraps that current line (which is fine for most normal typing). If you insert text into a line of make other complex changes, you'll need to do a manual `alt+q` to fix everything up.

Enable it with the `Rewrap: Toggle Auto-Wrap` command. It will show a brief message in the status bar.

<img src="https://user-images.githubusercontent.com/6125444/33222069-a14a32d2-d154-11e7-801a-d1aa760ad6f5.png" width="450" />

<img src="https://user-images.githubusercontent.com/6125444/33222173-7ce24208-d155-11e7-9bfb-057343bfd2b9.png" width="450" />

The command doesn't have a default keybinding, but you can add your own in the normal way by binding to the command `rewrap.toggleAutoWrap`.

Naturally it only applies in comments or markdown/text documents, so you may be fine with leaving it on all the time. You'll need to enable it each time you start vscode though, but I might change that so the on/off setting persists between sessions.

### Installation
Download this .zip file and **rename** it to a .vsix file: [rewrap-1.6.0-beta1.zip](https://github.com/stkb/Rewrap/files/1502372/rewrap-1.6.0-beta1.zip)

From the extensions sidebar in vscode:
1. Please uninstall the existing version of Rewrap first, to prevent conflicts.
2. From the "..." menu in the top right, choose "Install from VSIX.."
3. It should install v1.6.0-beta1 (restart needed)
4. If/when you go back to the marketplace version, again uninstall the beta version first.

I've also changed some of the general parsing code since the last version, so you may experience other bugs.

**Comment by gwf** [comment] 2017-11-26 23:13
I just tried the beta and quickly hit an error which I filed as a new issue.  LMK if you prefer that I add future problems with the beta in this thread or as separate issues.

**Comment by stkb** [comment] 2017-11-27 12:58
@gwf Thanks I've found the cause and will have a fix out soon. The problem seems to be restricted to LaTeX files.

It doesn't really matter but we can probably keep all issues with the beta here.

**Comment by stkb** [comment] 2017-11-27 19:37
Ok, here's beta 2 (have updated the comment above too)
[rewrap-1.6.0-beta2.zip](https://github.com/stkb/Rewrap/files/1507322/rewrap-1.6.0-beta2.zip)

As before, rename to .vsix and remove any existing version first.

Thanks for testing

**Comment by gwf** [comment] 2017-11-28 02:12
Looking good.  All of the problems from before are resolve.  Well done!

May I also suggest that you trigger auto-wrap on a space keystroke within the interior of a paragraph as well?   Obviously, you only need to trigger it when the right edge is to the right of the limit.  With this change, I think it will more closely approximate Emacs auto-fill-mode.

**Comment by stkb** [comment] 2017-11-28 16:09
Thanks, glad the bugs are fixed.

Do you have a plugin that does that that? Because afaik Emacs doesn't wrap when pressing space in the middle of a line (https://www.gnu.org/software/emacs/manual/html_node/emacs/Auto-Fill.html)

> Auto Fill mode does not refill entire paragraphs; it breaks lines but does not merge lines. Therefore, editing in the middle of a paragraph can result in a paragraph that is not correctly filled. To fill it, call the explicit fill commands (see Fill Commands). 

That's how it's working for me in both vanilla Emacs and with the AUCTeX plugin; it only wraps once the cursor is past the wrapping column again.
![emacs-auto-wrap](https://user-images.githubusercontent.com/6125444/33330169-6eb0ba8c-d45e-11e7-8388-ae1a22fa4422.gif)

The other way can be done, it just means having to re-adjust the whole contents of the paragraph each time, otherwise you have very undesirable results.

I could add the option for either I guess.

**Comment by gwf** [comment] 2017-11-30 19:24
@stkb, you're correct and my memory of how auto-fill-mode works in Emacs was wrong.  Sorry about that.

**Comment by fxn** [comment] 2017-12-07 13:52
Vim also supports this with `set fo+=a`, and it is how I set things up to write text documents like my journal.

**Comment by stkb** [comment] 2018-01-14 21:25
v1.6.0 is finally published. If you're using a beta version please uninstall (& restart) before re-installing from the marketplace.

**Comment by stkb** [comment] 2018-01-15 07:53
@fxn Thanks for the tip.

Closing this one now. Have created #65 for that enhancement.

**Closed by stkb** 2018-01-15 07:53 UTC
